steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sourcelens:$COMMIT_SHA", "."]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sourcelens:$COMMIT_SHA"
substitutions:
  _REGION: us-central1
  _REPOSITORY: sourcelens
